<div class="container">
    <div class="row">
        <h1>Person Table</h1>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTable">
                <thead>
                  <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Age</th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Rob</td>
                        <td>Doe</td>
                        <td>25</td>
                    </tr>
                    <tr>
                        <td>Jane</td>
                        <td>Smith</td>
                        <td>35</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
        
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->

<script>
    $(document).ready(function() {
        $('#dataTable').dataTable({
            "iDisplayLength": 10
        });
    });
    </script>